# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazykiq" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "e3fcd0c67efdb52fba0e84f462623eae58a336aa1be763e33d1c1152deb0b654"
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-darwin-arm64.tar.gz"
    end
    on_intel do
      sha256 "fd30e4b6dd61f2150ae39977cd8be4a37387194aeb7d20f6d6dcd97a7708ae90"
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-darwin-x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f4da772c5fba503cc1dad71640e09eda094a9bdb3093491dd6a1e35e9f300115"
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-linux-arm64.tar.gz"
    end
    on_intel do
      sha256 "d6a962006717756f54b956dfb3259052d9c686ec772c423a854e22efd1041454"
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-linux-x86_64.tar.gz"
    end
  end

  name "lazykiq"
  desc "A rich terminal UI for Sidekiq."
  homepage "https://github.com/kpumuk/lazykiq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazykiq"

  # No zap stanza required
end
