# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazykiq" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "2c768c3ce55b0ae0f4255b1c1201b7b08b3b67eb432687ac5999a22111891a3a"
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-darwin-x86_64.tar.gz"
    end
    on_arm do
      sha256 "2b3063adb52ee570d5b2794cc0141f6ee3c0c352798f13ff6b67d2667016d72d"
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83b800908a80542c72a9d5f1c30ae53688396f610b2dfb1cfc8388c518de8e0a"
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-linux-x86_64.tar.gz"
    end
    on_arm do
      sha256 "89cadb892dc829aee727859fbfd67d80dc5952551952dbf74c3c22ec4d54f8fd"
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-linux-arm64.tar.gz"
    end
  end

  name "lazykiq"
  desc "A rich terminal UI for Sidekiq."
  homepage "https://github.com/kpumuk/lazykiq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazykiq"

  # No zap stanza required

end
