# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazykiq" do
  name "lazykiq"
  desc "A rich terminal UI for Sidekiq."
  homepage "https://github.com/kpumuk/lazykiq"
  version "0.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazykiq"

  on_macos do
    on_intel do
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-darwin-x86_64.tar.gz"
      sha256 "06a5f7c588b94a630aa4f6e1a63f792f58f2ce06d097f7f3d0856f641453deff"
    end
    on_arm do
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-darwin-arm64.tar.gz"
      sha256 "7c5e36bae6fff957f993812f7d9dba5a1c6f43a9e0684a0e141abcbde4ab066f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-linux-x86_64.tar.gz"
      sha256 "05f8c4dcd72e6c6cc00643c2a3b3d6eb8e3d00e5df86f24ffb4148b097cc3837"
    end
    on_arm do
      url "https://github.com/kpumuk/lazykiq/releases/download/v#{version}/lazykiq-#{version}-linux-arm64.tar.gz"
      sha256 "d6a803de1253bb57f0250e0e5e421fc3333e793600d974213a69dda37db4cc22"
    end
  end

  # No zap stanza required
end
